### ISSUE TITLE
Node v8 crypto.pbkdf2 "digest" argument required

### ISSUE THREAD

**Issue by ryanchantler** [zemirco/couch-pwd#5]
With Node v8 the crypto.pbkdf2(password, salt, iterations, keylen, digest, callback) function requires "digest".

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:635:11)
    at Object.exports.pbkdf2 (crypto.js:623:10)
    at RandomBytes.ondone (.../node_modules/couch-pwd/index.js:55:14)

**Comment by Charles546** [comment]
The thing frustrates me is that the fix was apparently merged in March.  But the maintainer didn't care to create a new release and update npm.  Anything that was maintained by individuals instead of a committee of some sort usually fails to provide any guarantee of quality.  One choice would probably be to fork the code and maintain the fork yourself and never come back here.

**Comment by Prefect001** [comment]
Haven't found a solution. I tried using previous versions of mocha but it still didn't work. All my mocha tests are failing because of this
